### PR TITLE
Added caching to speed up datewise missed classes, fixed Travis badge

### PR DESCRIPTION
**Pull request by PalAditya**
This significantly speeds up the fetching of datewise missed attendance after fetching it once, as we iterate only over the dates that we hadn't seen.
Also, modified the travis badge to point to the dsciitbbs repo.

### CODE REVIEW

**Comment by PalAditya** [comment]
@apsknight , @MadhavChoudhary please check if the file handling works correctly in Mac/Linux (**Note**: The travis CI check should really be made more extensive...)
@rk36 this fixes the speed concern you had over the date fetching method 😄

**Comment by madhavtummala** [comment]
The code is working on macOS.
`sudo` is required. Else it will fail.
Don't think the data output is correct in my case though.
Caching also works.

**Review by madhavtummala — COMMENTED** [review]
The function MissedClassDates maybe a little inefficient. In a quick glance, it looked like, it does a query for every date in the range.
I think it would be more efficient to start with the entire period, then break it into *two equal halves*, check in each half only if `attended < total` else *discard* that range. Kind of like binary search. Worst case time complexity will be 0(n) tough. @PalAditya what do you say. Is the optimisation worth the implementation pain? Although it is the change to be expected from @rk36 in his original pull request.

**Comment by madhavtummala** [comment]
The code is working properly 👍

**Comment by madhavtummala** [comment]
The optimisation will not matter much when the caching is turned on. So, it can be actually skipped.

**Comment by madhavtummala** [comment]
@PalAditya I agree that Travis CI test is very weak right now.
Open an Issue, we will fix that next.

**Comment by PalAditya** [comment]
> The function MissedClassDates maybe a little inefficient. In a quick glance, it looked like, it does a query for every date in the range.
> I think it would be more efficient to start with the entire period, then break it into _two equal halves_, check in each half only if `attended < total` else _discard_ that range. Kind of like binary search. Worst case time complexity will be 0(n) tough. @PalAditya what do you say. Is the optimisation worth the implementation pain? Although it is the change to be expected from @rk36 in his original pull request.

Pretty nice idea! I think we can look into this too 😄 
The code would be a little *complicated* though 🤔 
Should we merge this now and open a issue for it if someone wishes to optimize that?

**Comment by madhavtummala** [comment]
@PalAditya Yeah Sure. 
This pull request serves its purpose. Thanks for the contribution 👍

**Pull request merged**
